id: I027F136A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T02:30:08+00:00'
last_modified: '2022-06-07T18:39:02.287819+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7054
  title: གཉེན་སྒྲིག་ཁྱིམ་ཚང་གི་ཁྲིམས་ལུགས་ཤེས་བྱའི་དྲིས་ལན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4A21:
      image_group_id: I3CN7056
      title: ''
      total_pages: 244
      order: 1
      base_file: 4A21.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
