id: P003250
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7054
  title: གཉེན་སྒྲིག་ཁྱིམ་ཚང་གི་ཁྲིམས་ལུགས་ཤེས་བྱའི་དྲིས་ལན།
  author: ''
  volumes:
    787029fe3b1e442d98918d5db4d64582:
      image_group_id: I3CN7056
      title: ''
      volume_number: 1
      total_pages: 244
